patch_sync: Validate patches during parsing
At present, patch_sync will just ignore invalid patches
when trying to find new values during transposing. This has
worked fine for a while, but if someone accidentally puts
an incorrect platform type or omits the patch file, we
really should report an error.

This CL adds the error reporting functionality.

Example error:
mobiletc-prebuild@chrotomation:~/$ /tmp/patch_sync_wrapper.sh
Error: finding new patches for chromiumos

Caused by:
    Patch cherry/f1764d5b594ff6edbf8d17d196eb0b7a653ac0fc.patch did
    not apply to platform chromiumos

BUG=b:268657960
TEST=cargo test
TEST=Tested on chrotomation

Change-Id: I3d386d930da5b61b3d887e479b3d133100d236f6
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/4240721
Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
Tested-by: Jordan Abrahams-Whitehead <ajordanr@google.com>
Reviewed-by: George Burgess <gbiv@chromium.org>
Commit-Queue: Jordan Abrahams-Whitehead <ajordanr@google.com>