llvm_tool: make either --sha or --differential required.
This fixed the following error when only --sha or --differential is
used.

TypeError: can only concatenate list (not "NoneType") to list

BUG=b:187554374
TEST=get_upstream_patch.py --chroot_path <chroot> --start llvm --sha <sha>
TEST=get_upstream_patch.py --chroot_path <chroot> --start llvm --differential <rev>
TEST=get_upstream_patch.py --chroot_path <chroot> --start llvm

Change-Id: Ie50e1c081a6a41859d7e4db7a2d815e48b84fa3d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/2898172
Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
Tested-by: Jian Cai <jiancai@google.com>